/*
 * This file is part of CryoRegenesis, a Better Rimworlds Project.
 *
 * Copyright © 2020-2026 Theodore R. Smith
 * Author: Theodore R. Smith <hopeseekr@gmail.com>
 *
 * This file is licensed under the MIT License.
 */

using RimWorld;
using RimWorld.QuestGen;
using Verse;

#if RIMWORLD15 || RIMWORLD16
using LudeonTK;
#endif

namespace BetterRimworlds.CryoRegenesis;

public class QuestNode_StartRoyaltyRegenesisChain : QuestNode
{
    protected override bool TestRunInt(Slate slate)
    {
        return ModsConfig.RoyaltyActive;
    }

    protected override void RunInt()
    {
        // Prefer the GameComponent path; this node exists so the script def is valid
        // if generated by the storyteller. The persistent quest is created by the system.
        RoyaltyRegenesisQuestSystem system = Current.Game?.GetComponent<RoyaltyRegenesisQuestSystem>();
        if (system == null)
        {
            return;
        }

        system.DebugStartAt(RoyaltyRegenesisStage.RulerPrisoners);
    }
}

/// Placeholder root for per-contract quest script defs. Real contract quests are built in code.
public class QuestNode_RoyaltyRegenesisContractPlaceholder : QuestNode
{
    protected override bool TestRunInt(Slate slate)
    {
        return true;
    }

    protected override void RunInt()
    {
    }
}
